src/Entity/Contact.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Config\CommunicationType;
use App\Repository\ContactRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $note = null;

    /** @var Collection<int, CommunicationChannel> */
    #[ORM\OneToMany(targetEntity: CommunicationChannel::class, mappedBy: 'contact', cascade: ['persist'], orphanRemoval: true)]
    private Collection $communicationChannels;

    #[ORM\ManyToOne(inversedBy: 'contacts')]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?Company $company = null;

    public function __construct()
    {
        $this->communicationChannels = new ArrayCollection();
    }

    public static function create(
        string $firstName,
        string $lastName,
        Company $company,
    ): Contact
    {
        if (empty(trim($firstName)) || empty(trim($lastName))) {
            throw new InvalidArgumentException('Contact must have first and last name');
        }

        return (new self)
            ->setFirstName($firstName)
            ->setLastName($lastName)
            ->setCompany($company)
        ;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;
        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;
        return $this;
    }

    /** @return Collection<int, CommunicationChannel> */
    public function getCommunicationChannels(): Collection
    {
        return $this->communicationChannels;
    }

    public function addCommunicationChannel(CommunicationChannel $communicationChannels): self
    {
        if (!$this->communicationChannels->contains($communicationChannels)) {
            $this->communicationChannels->add($communicationChannels);
            $communicationChannels->setContact($this);
        }
        return $this;
    }

    public function removeCommunicationChannel(CommunicationChannel $communicationChannels): self
    {
        if ($this->communicationChannels->removeElement($communicationChannels)) {
            // set the owning side to null (unless already changed)
            if ($communicationChannels->getContact() === $this) {
                $communicationChannels->setContact(null);
            }
        }
        return $this;
    }

    public function withCommunicationChannel(CommunicationType $type, string $value): self
    {
        return $this->addCommunicationChannel(CommunicationChannel::create($type, $value, $this));
    }

    public function withEmail(string $email): self
    {
        return $this->withCommunicationChannel(CommunicationType::EMAIL, $email);
    }

    public function withWorkPhone(string $phone): self
    {
        return $this->withCommunicationChannel(CommunicationType::PHONE_WORK, $phone);
    }

    public function withPersonalPhone(string $phone): self
    {
        return $this->withCommunicationChannel(CommunicationType::PHONE_PERSONAL, $phone);
    }

    public function communicationChannelsByType(CommunicationType|string $type): array
    {
        if (!($type instanceof CommunicationType)) {
            $type = CommunicationType::from($type);
        }

        return $this->communicationChannels
            ->filter(fn(CommunicationChannel $cc) => $cc->getType() === $type)
            ->toArray()
        ;
    }

    public function getEmails(): array
    {
        return $this->communicationChannelsByType(CommunicationType::EMAIL);
    }

    public function getPhones(): array
    {
        return array_merge(
            $this->communicationChannelsByType(CommunicationType::PHONE_WORK),
            $this->communicationChannelsByType(CommunicationType::PHONE_PERSONAL),
        );
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;
        return $this;
    }
}

src/Entity/Ticket.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use LogicException;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Project $project = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TicketStatus $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /** @var Collection<int, Tag> */
    #[ORM\ManyToMany(targetEntity: Tag::class)]
    #[ORM\OrderBy(['id' => 'ASC'])]
    private Collection $tags;

    /** @var Collection<int, TicketTask> */
    #[ORM\OneToMany(targetEntity: TicketTask::class, mappedBy: 'ticket', orphanRemoval: true, cascade: ['persist'])]
    private Collection $tasks;

    #[ORM\Column(options: ['default' => 0])]
    private int $displayOrder = 0;

    #[ORM\Column(options: ['default' => false])]
    private bool $isArchived = false;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->tasks = new ArrayCollection();
    }

    public static function create(
        Project $project,
        string $title,
        TicketStatus $ticketStatus,
        ?string $description,
        ?array $tags = null,
    ): Ticket
    {
        $ticket = (new self)
            ->setProject($project)
            ->setTitle($title)
            ->setStatus($ticketStatus)
            ->setDescription($description)
        ;

        foreach ($tags as $tag) {
            $ticket->addTag($tag);
        }

        return $ticket;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getStatus(): ?TicketStatus
    {
        return $this->status;
    }

    public function setStatus(?TicketStatus $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);
        return $this;
    }

    /**
     * @return Collection<int, TicketTask>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(TicketTask $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setTicket($this);
        }

        return $this;
    }

    public function removeTask(TicketTask $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getTicket() === $this) {
                $task->setTicket(null);
            }
        }

        return $this;
    }

    public function getDisplayOrder(): ?int
    {
        return $this->displayOrder;
    }

    public function setDisplayOrder(int $displayOrder): self
    {
        $this->displayOrder = $displayOrder;
        return $this;
    }

    public function isArchived(): bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(bool $isArchived): self
    {
        if (!$isArchived && $this->project->isFinished()) {
            throw new LogicException('Cannot unarchive ticket of finished project');
        }

        $this->isArchived = $isArchived;
        return $this;
    }

    public function isEditable(): bool
    {
        return !$this->isArchived && !$this->project->isFinished();
    }
}

src/Entity/User.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Config\UserStatus;
use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use LogicException;
use SensitiveParameter;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity('email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    public const DEFAULT_ROLE = 'ROLE_USER';

    public const ADMIN_ROLE = 'ROLE_ADMIN';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\Email(mode: Assert\Email::VALIDATION_MODE_HTML5_ALLOW_NO_TLD)]
    private ?string $email = null;

    /** @var string[] The user roles */
    #[ORM\Column(type: Types::JSON, options: ['jsonb' => true])]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $position = null;

    /** @var Collection<int, Project> */
    #[ORM\ManyToMany(targetEntity: Project::class, mappedBy: 'managers')]
    private Collection $managedProjects;

    #[ORM\Column(enumType: UserStatus::class)]
    private UserStatus $status = UserStatus::PENDING;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $lastLogin = null;

    public function __construct()
    {
        $this->managedProjects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function isAdmin(): bool
    {
        return in_array(self::ADMIN_ROLE, $this->roles);
    }

    /**
     * @see UserInterface
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = self::DEFAULT_ROLE;
        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function addRole(string $role): self
    {
        $this->roles = array_unique([...$this->roles, $role]);
        return $this;
    }

    public function removeRole(string $role): self
    {
        $this->roles = array_diff($this->roles, [$role]);
        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(#[SensitiveParameter] string $password): self
    {
        if (!$this->isRegistered()) {
            $this->status = UserStatus::ACTIVE;
        }
        $this->password = $password;
        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);
        return $data;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(?string $position): self
    {
        $this->position = $position;
        return $this;
    }

    public function getDisplayName(): string
    {
        $fn = $this->getFirstName() ?? '';
        $ln = $this->getLastName() ?? '';
        return trim($fn . ' ' . $ln . ' (' . $this->email . ')');
    }

    /**
     * @return Collection<int, Project>
     */
    public function getManagedProjects(): Collection
    {
        return $this->managedProjects;
    }

    public function addManagedProject(Project $project): self
    {
        if (!$this->managedProjects->contains($project)) {
            $this->managedProjects->add($project);
            $project->addManager($this);
        }

        return $this;
    }

    public function removeManagedProject(Project $project): self
    {
        if ($this->managedProjects->removeElement($project)) {
            $project->removeManager($this);
        }
        return $this;
    }

    public function getStatus(): UserStatus
    {
        return $this->status;
    }

    public function setStatus(UserStatus $status): self
    {
        if (($status === UserStatus::PENDING) === $this->isRegistered()) {
            throw new LogicException($this->isRegistered()
                ? 'Cannot change user status to "pending" after registration'
                : 'User is not fully registered, cannot change status from "pending"'
            );
        }

        $this->status = $status;
        return $this;
    }

    public function isActive(): bool
    {
        return $this->status === UserStatus::ACTIVE;
    }

    public function isRegistered(): bool
    {
        return !empty($this->password) && $this->status !== UserStatus::PENDING;
    }

    public function getLastLogin(): ?DateTimeImmutable
    {
        return $this->lastLogin;
    }

    public function setLastLogin(DateTimeImmutable $lastLogin): self
    {
        $this->lastLogin = $lastLogin;
        return $this;
    }
}

templates/listings/_companies.html.twig
<twig:Common:Listing entityClassName="{{ entityClassName }}"  {{ ...(companiesListingProps ?? {}) }}>
    <twig:block name="headers_action_right">
        <twig:Elements:Button data-action="live#emit" data-live-event-param="company:edit">
            <twig:ux:icon name="tabler:building-plus" class="mr-2"/>New Company
        </twig:Elements:Button>
    </twig:block>
    <twig:block name="table_head">
        <twig:Elements:Th>Name</twig:Elements:Th>
        <twig:Elements:Th>Contacts</twig:Elements:Th>
        <twig:Elements:Th>Projects</twig:Elements:Th>
        <twig:Elements:Th class="text-right whitespace-nowrap w-8">Actions</twig:Elements:Th>
    </twig:block>
    <twig:block name="table_row">
        <twig:Elements:Td class="text-gray-900">
            <twig:Elements:Button variant="link" href="{{ path('app_user_company_view', {id: item.id}) }}">
                {{- item.name -}}
            </twig:Elements:Button>
        </twig:Elements:Td>
        <twig:Elements:Td>{{ item.contacts.count }}</twig:Elements:Td>
        <twig:Elements:Td>{{ item.projects.count }}</twig:Elements:Td>
        <twig:Elements:Td class="text-gray-900 whitespace-nowrap text-right">
            <twig:Elements:Dropdown variant='short'>
                <twig:Elements:DropdownButton
                    data-action="live#emit"
                    data-live-event-param="company:edit"
                    data-live-company-param="{{ item.id }}"
                >
                    <twig:ux:icon name="tabler:pencil" class="w-4 h-4" /> Edit
                </twig:Elements:DropdownButton>
                <twig:Elements:DeleteButton
                    button:class="justify-start"
                    button:width="full"
                    action="{{ path('app_user_company_delete', {id: item.id}) }}"
                    token="{{ csrf_token('delete-company-' ~ item.id) }}"
                />
            </twig:Elements:Dropdown>
        </twig:Elements:Td>
    </twig:block>
    <twig:block name="post_table">
        <twig:Elements:Modal name="company">
            <twig:User:CompanyEdit modalName="company"/>
        </twig:Elements:Modal>
    </twig:block>
</twig:Common:Listing>

templates/listings/_contacts.html.twig
<twig:Common:Listing entityClassName="{{ entityClassName }}"  {{ ...(contactsListingProps ?? {}) }}>
    <twig:block name="headers_action_right">
        <twig:Elements:Button data-action="live#emit" data-live-event-param="contact:edit">
            <twig:ux:icon name="tabler:user-plus" class="mr-2"/>New Contact
        </twig:Elements:Button>
    </twig:block>
    <twig:block name="table_head">
        <twig:Elements:Th>Name</twig:Elements:Th>
        <twig:Elements:Th>Company</twig:Elements:Th>
        <twig:Elements:Th>Email</twig:Elements:Th>
        <twig:Elements:Th class="text-right whitespace-nowrap w-8">Actions</twig:Elements:Th>
    </twig:block>
    <twig:block name="table_row">
        <twig:Elements:Td class="text-gray-900">
            <twig:Elements:Button variant="link" href="{{ path('app_user_contact_view', {id: item.id}) }}">
                {{ item.firstName }} {{ item.lastName }}
            </twig:Elements:Button>
        </twig:Elements:Td>
        <twig:Elements:Td>
            <a
                href="{{ path('app_user_company_view', {id: item.company.id}) }}"
                class="text-gray-500 hover:text-gray-900 hover:underline"
            >{{ item.company.name }}</a>
        </twig:Elements:Td>
        <twig:Elements:Td>
            {%- for email in item.emails  -%}
                <twig:Elements:Button variant="link" href="mailto:{{ email.value }}">
                    {{ email.value }}
                </twig:Elements:Button>
            {%- endfor -%}
        </twig:Elements:Td>
        <twig:Elements:Td class="text-gray-900 whitespace-nowrap text-right">
            <twig:Elements:Dropdown variant='short'>
                <twig:Elements:DropdownButton
                    data-action="live#emit"
                    data-live-event-param="contact:edit"
                    data-live-contact-param="{{ item.id }}"
                >
                    <twig:ux:icon name="tabler:pencil" class="w-4 h-4" /> Edit
                </twig:Elements:DropdownButton>
                <twig:Elements:DeleteButton
                    button:class="justify-start"
                    button:width="full"
                    action="{{ path('app_user_contact_delete', {id: item.id}) }}"
                    token="{{ csrf_token('delete-contact-' ~ item.id) }}"
                />
            </twig:Elements:Dropdown>
        </twig:Elements:Td>
    </twig:block>
    <twig:block name="post_table">
        <twig:Elements:Modal name="contact">
            <twig:User:ContactEdit modalName="contact"/>
        </twig:Elements:Modal>
    </twig:block>
</twig:Common:Listing>

templates/listings/_projects.html.twig
<twig:Common:Listing entityClassName="{{ entityClassName }}"  {{ ...(projectsListingProps ?? {}) }}>
    <twig:block name="headers_action_right">
        <twig:Elements:Button data-action="live#emit" data-live-event-param="project:edit">
            <twig:ux:icon name="tabler:folder-plus" class="mr-2"/>New Project
        </twig:Elements:Button>
    </twig:block>
    <twig:block name="table_head">
        <twig:Elements:Th>Name</twig:Elements:Th>
        <twig:Elements:Th>Managers</twig:Elements:Th>
        <twig:Elements:Th class="w-8">Status</twig:Elements:Th>
        <twig:Elements:Th class="text-right whitespace-nowrap w-8">Actions</twig:Elements:Th>
    </twig:block>
    <twig:block name="table_row">
        <twig:Elements:Td class="text-gray-900">
            <twig:Elements:Button variant="link" href="{{ path('app_user_project_view', {id: item.id}) }}">
                {{ item.name }}
            </twig:Elements:Button>
        </twig:Elements:Td>
        <twig:Elements:Td>
            {% if item.managers|length > 0 %}
                <div class="flex flex-wrap gap-1">
                    {% for manager in item.managers %}
                        <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
                            {{- manager.displayName -}}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
                -
            {% endif %}
        </twig:Elements:Td>
        <twig:Elements:Td>
            <twig:Elements:Pill
                variant="{{ item.isFinished ? 'disabled' : 'default' }}"
                content="{{ item.isFinished ? 'Finished' : 'Active' }}"
            />
        </twig:Elements:Td>
        <twig:Elements:Td class="text-gray-900 whitespace-nowrap text-right">
            <twig:Elements:Dropdown variant='short'>
                {%- if is_granted_for_user(app.user, 'PROJECT_EDIT', item) -%}
                <twig:Elements:DropdownButton
                    data-action="live#emit"
                    data-live-event-param="project:edit"
                    data-live-project-param="{{ item.id }}"
                >
                    <twig:ux:icon name="tabler:pencil" class="w-4 h-4" /> Edit
                </twig:Elements:DropdownButton>
                {%- endif -%}

                {%- if is_granted_for_user(app.user, 'PROJECT_FINISH', item) -%}
                <twig:Elements:DropdownButton
                    data-action="live#action"
                    data-live-action-param="toggleProjectStatus"
                    data-live-project-param="{{ item.id }}"
                >
                    <twig:ux:icon class="w-4 h-4" name="{{ item.finished ? 'tabler:player-play' : 'tabler:check' }}"/>
                    {{  item.finished ? 'Mark as active' : 'Mark as finished'   -}}
                </twig:Elements:DropdownButton>
                {%- endif -%}

                {%- if is_granted_for_user(app.user, 'PROJECT_DELETE', item) -%}
                <twig:Elements:DeleteButton
                    button:class="justify-start"
                    button:width="full"
                    action="{{ path('app_user_project_delete', {id: item.id}) }}"
                    token="{{ csrf_token('delete-project-' ~ item.id) }}"
                />
                {%- endif -%}
            </twig:Elements:Dropdown>
        </twig:Elements:Td>
    </twig:block>
    <twig:block name="post_table">
        <twig:Elements:Modal name="project">
            <twig:User:ProjectEdit modalName="project"/>
        </twig:Elements:Modal>
    </twig:block>
</twig:Common:Listing>

templates/listings/_tickets.html.twig
<twig:Common:Listing entityClassName="{{ entityClassName }}" {{ ...(ticketsListingProps ?? {}) }}>
    <twig:block name="headers_action_right">
        <twig:Elements:Button data-action="live#emit" data-live-event-param="ticket:edit">
            <twig:ux:icon name="tabler:ticket" class="mr-2"/>New Ticket
        </twig:Elements:Button>
    </twig:block>
    <twig:block name="table_head">
        <twig:Elements:Th class="w-8">ID</twig:Elements:Th>
        <twig:Elements:Th>Title</twig:Elements:Th>
        <twig:Elements:Th>Project</twig:Elements:Th>
        <twig:Elements:Th class="text-center w-8">Status</twig:Elements:Th>
        <twig:Elements:Th class="text-center w-8">Progress</twig:Elements:Th>
        <twig:Elements:Th class="text-right whitespace-nowrap w-8">Actions</twig:Elements:Th>
    </twig:block>
    <twig:block name="table_row">
        <twig:Elements:Td class="text-gray-500">{{ item.ticket.id }}</twig:Elements:Td>
        <twig:Elements:Td class="{{ item.ticket.archived ? 'line-through' : 'text-gray-900' }}">
            {{ item.ticket.title }}
        </twig:Elements:Td>
        <twig:Elements:Td>
            <a
                href="{{ path('app_user_project_view', {id: item.ticket.project.id}) }}"
                class="text-gray-500 hover:text-gray-900 hover:underline"
            >{{ item.ticket.project.name }}</a>
        </twig:Elements:Td>
        <twig:Elements:Td class="text-center">
            <twig:Elements:Pill content="{{ item.ticket.status.name }}"/>
        </twig:Elements:Td>
        <twig:Elements:Td class="text-center">
            {% set percentage = item.tasks > 0 ? ((item.completedTasks / item.tasks) * 100)|round : 0 %}
            <twig:Elements:Pill
                variant="{{ percentage == 100 ? 'green' : (percentage > 0 ? 'yellow' : 'default') }}"
                content="{{ item.completedTasks }}/{{ item.tasks }} ({{ percentage }}%)"
            />
        </twig:Elements:Td>
        <twig:Elements:Td class="text-gray-900 whitespace-nowrap text-right">
            <twig:Elements:Dropdown variant='short'>
                <twig:Elements:DropdownButton
                    data-action="live#emit"
                    data-live-event-param="ticket:view"
                    data-live-ticket-param="{{ item.ticket.id }}"
                >
                    <twig:ux:icon name="tabler:ticket" class="w-4 h-4" /> View
                </twig:Elements:DropdownButton>

                {%- if is_granted_for_user(app.user, 'TICKET_EDIT', item.ticket) -%}
                    <twig:Elements:DropdownButton
                        data-action="live#emit"
                        data-live-event-param="ticket:edit"
                        data-live-ticket-param="{{ item.ticket.id }}"
                    >
                        <twig:ux:icon name="tabler:pencil" class="w-4 h-4" /> Edit
                    </twig:Elements:DropdownButton>
                {%- endif -%}

                {%- if is_granted_for_user(app.user, 'TICKET_ARCHIVE', item.ticket) -%}
                    <twig:Elements:DropdownButton
                        data-action="live#emit"
                        data-live-event-param="ticket:toggle-archive"
                        data-live-ticket-param="{{ item.ticket.id }}"
                    >
                        {% if item.ticket.archived %}
                            <twig:ux:icon name="tabler:archive-off" class="w-4 h-4" /> Unarchive
                        {% else %}
                            <twig:ux:icon name="tabler:archive" class="w-4 h-4" /> Archive
                        {% endif %}
                    </twig:Elements:DropdownButton>
                {%- endif -%}

                <twig:Elements:DeleteButton
                    button:class="justify-start"
                    button:width="full"
                    action="{{ path('app_user_ticket_delete', {id: item.ticket.id}) }}"
                    token="{{ csrf_token('delete-ticket-' ~ item.ticket.id) }}"
                />
            </twig:Elements:Dropdown>
        </twig:Elements:Td>
    </twig:block>
    <twig:block name="post_table">
        <twig:Elements:Modal name="ticket">
            <twig:User:TicketViewEdit modalName="ticket"/>
        </twig:Elements:Modal>
    </twig:block>
</twig:Common:Listing>

templates/listings/listing.html.twig
{% extends 'default_layout.html.twig' %}

{% block title %}{{ title }}{% endblock %}
{% block header_title %}{{ headerTitle }}{% endblock %}

{% block content %}
    {{ include('listings/' ~ listing) }}
{% endblock %}